apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: platform-one
spec:
  ## Platform
  image_pull_policy: IfNotPresent
  # Development purposes only
  no_log: false
  ## uncomment to test bundle certs
  # bundle_cacert_secret: gateway-custom-certs

  ####################
  ## Extra Settings ##
  ####################
#  extra_settings:
#    - setting: CSRF_TRUSTED_ORIGINS
#      value:
#        - https://my-aap-domain.com

  ################
  ## Components ##
  ################
  controller:
    disable: false
  eda:
    disable: false
  hub:
    disabled: false
    ## uncomment if using file storage for Content pod
    #storage_type: file
    #file_storage_storage_class: nfs-local-rwx
    #file_storage_size: 10Gi
    ## Trick this file
    ## uncomment if using S3 storage for Content pod
    storage_type: S3
    object_storage_s3_secret: s3-secret

    ## uncomment if using Azure storage for Content pod
    # storage_type: azure
    # object_storage_azure_secret: azure-secret-name
  lightspeed:
    disabled: true


# End state:
# * Automation controller deployed and named: platform-one-controller
# * * Event-Driven Ansible deployed and named: platform-one-eda
# * * Automation hub deployed and named: platform-one-hub

