apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nested-podman-clusterrole
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nested-podman
  resources:
  - securitycontextconstraints
  verbs:
  - use