apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nested-podman-rolebinding
  namespace: aap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nested-podman-clusterrole
subjects:
- kind: ServiceAccount
  name: automation-job-podman
  namespace: aap